local colors = require("dilly.colors")

return {

	-- blink.cmp
	BlinkCmpMenu = { link = "Pmenu" },
	BlinkCmpMenuSelection = { link = "PmenuSel" },
	-- BlinkCmpMenuBorder = { fg = theme.ui.bg_search, bg = theme.ui.pmenu.bg },
	BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
	BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
	-- BlinkCmpLabel = { fg = theme.ui.pmenu.fg },
	-- BlinkCmpLabelMatch = { fg = theme.syn.fun },
	-- BlinkCmpLabelDetails = { fg = theme.syn.comment },
	-- BlinkCmpLabelDeprecated = { fg = theme.syn.comment, strikethrough = true },
	-- BlinkCmpGhostText = { fg = theme.syn.comment },
	BlinkCmpDoc = { link = "NormalFloat" },
	BlinkCmpDocBorder = { link = "FloatBorder" },
	BlinkCmpDocCursorLine = { link = "Visual" },
	BlinkCmpSignatureHelp = { link = "NormalFloat" },
	BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
	BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },

	-- BlinkCmpKind = { fg = theme.ui.fg_dim },
	-- BlinkCmpKindText = { fg = theme.ui.fg },
	BlinkCmpKindMethod = { link = "@function.method" },
	BlinkCmpKindFunction = { link = "Function" },
	BlinkCmpKindConstructor = { link = "@constructor" },
	BlinkCmpKindField = { link = "@variable.member" },
	-- BlinkCmpKindVariable = { fg = theme.ui.fg_dim },
	BlinkCmpKindClass = { link = "Type" },
	BlinkCmpKindInterface = { link = "Type" },
	BlinkCmpKindModule = { link = "@module" },
	BlinkCmpKindProperty = { link = "@property" },
	BlinkCmpKindUnit = { link = "Number" },
	BlinkCmpKindValue = { link = "String" },
	BlinkCmpKindEnum = { link = "Type" },
	BlinkCmpKindKeyword = { link = "Keyword" },
	BlinkCmpKindSnippet = { link = "Special" },
	BlinkCmpKindColor = { link = "Special" },
	BlinkCmpKindFile = { link = "Directory" },
	BlinkCmpKindReference = { link = "Special" },
	BlinkCmpKindFolder = { link = "Directory" },
	BlinkCmpKindEnumMember = { link = "Constant" },
	BlinkCmpKindConstant = { link = "Constant" },
	BlinkCmpKindStruct = { link = "Type" },
	BlinkCmpKindEvent = { link = "Type" },
	BlinkCmpKindOperator = { link = "Operator" },
	BlinkCmpKindTypeParameter = { link = "Type" },
	BlinkCmpKindCopilot = { link = "String" },

	-- Snacks Picker
	SnacksPicker = { link = "Pmenu" },
	SnacksPickerBorder = { link = "Pmenu" },
	SnacksPickerDir = { fg = "NONE", bg = "NONE", nocombine = true },
	SnacksPickerDirectory = { fg = "NONE", bg = "NONE", nocombine = true },
	SnacksIndent = { fg = colors.gainsboro, bg = "NONE", nocombine = true },
	SnacksPickerListCursorLine = { link = "PmenuSel" },
	SnacksPickerPreviewCursorLine = { fg = "NONE", bg = "NONE", nocombine = true },
}
